"""
CLEANING_RULES.PY - MODULO SAT
Contiene el repositorio maestro para la reparacion de Mojibake y recuperacion 
de codificacion (Encoding Recovery) detectada en archivos masivos del SAT.
"""

# ==============================================================================
# 1. MOTOR DE REPARACION DE MOJIBAKE (Encoding Recovery)
# ==============================================================================
REEMPLAZOS_MOJIBAKE = {
    'A¯ ¿ ¿AGA': 'ÑAGA',
    'A¯ ¿ ¿IGA': 'ÑIGA',
    'A¯ ¿ ¿UELOS': 'ÑUELOS',
    'A¯ ¿ ¿A': 'ÑA',
    'A¯ ¿ ¿O': 'ÑO',
    'A¯ ¿ ¿EZ': 'ÑEZ',
    'A¯ ¿ ¿OS': 'ÑOS',
    'A¯ ¿ ¿': 'Ñ', 

    # --- Casos Criticos: Triple Encoding & Corrupcion Profunda ---
    'ÃƒÂƒÃ¢Â€Â˜': 'Ñ', 
    'ÃƒÂƒÃ¢Â€Â': 'Ñ', 
    'Ã¯Â¿Â½': 'Ñ', 
    'A¯ ¿ ½': 'Ñ',
    'DÂ¥': 'D', 
    'D ¥': 'D',
    'â€¦': '', 
    ' ¦': '', 
    'Â·': '',

    # --- Alta Prioridad: Errores de Lectura Comunes ---
    'ARÑR': 'O', 
    'CIA “N': 'CION', 
    'CIA“N': 'CION', 
    '“N': 'ON', 
    '“': 'O', 
    'A “': 'O',

    # --- Double Encoding (UTF-8 as Latin-1) ---
    'ÃƒÂ±': 'Ñ', 
    'ÃƒÂ‘': 'Ñ', 
    'Ãƒ ': 'Ñ', 
    'Ãƒ?': 'Ñ', 
    'Ãƒ': 'Ñ', 
    'Ã‰': 'E', 
    'Ã“': 'O', 
    'Ã”': 'O', 
    'Ã…': 'A', 
    'Ã‘': 'Ñ', 
    'Ã±': 'Ñ', 
    'Ã¡': 'A', 
    'Ã©': 'E', 
    'Ã­': 'I', 
    'Ã³': 'O', 
    'Ãº': 'U', 
    'Ãš': 'U',
    'Ã‡': ' ', 
    'ÃŒ': 'U', 
    'Ã.': 'Ñ', 
    'A‰': 'E',
    'A“': 'O', 
    'A Œ': 'O',
    'A¨': 'E', 
    'A©': 'E', 
    'A ©': 'E', 
    '©': 'E',
    'Ã\x8d': 'I', 
    'Ã\xad': 'I', 
    'Ã\x81': 'A', 
    'AGUIAƑ˜': 'Ñ', 
    'MARÃA': 'MARIA', 
    'ALCALDÃA': 'ALCALDIA', 
    'GARCÃA': 'GARCIA',

    # --- Hexadecimales, Simbolos y Residuos de Parsing ---
    '¥': 'Ñ',
    'Ã¥': 'Ñ',
    'Â¥': 'Ñ',
    'ÃA': 'IA', 
    'Ƒ˜': 'Ñ', 
    '˜': '', 
    'Ƒ': '', 
    '¨': '',
    '’': '', 
    '‘': '', 
    '´': '', 
    '²': 'O', 
    '¹': 'U', 
    '™': '', 
    '¬': 'I', 
    'Œ': 'O', 
    '±': 'Ñ', 
    'A ±': 'Ñ', 
    'A O': 'Ñ', 
    'A ‰': 'E',
    'Ï¿½': '', 
    '°': '', 
    'º': '', 
    '§': '', 
    '¼': 'U',

    # --- Patrones de Incertidumbre e Interrogantes ---
    'Ã ': 'A', 
    'Ã': 'A', 
    'GARC?A': 'GARCIA', 
    'GARC A': 'GARCIA', 
    'G?MEZ': 'GOMEZ', 
    'G MEZ': 'GOMEZ',
    'P?REZ': 'PEREZ', 
    ' P REZ': ' PEREZ', 
    'ORDO?EZ': 'ORDOÑEZ', 
    'ORDO EZ': 'ORDOÑEZ', 
    'LUC?A': 'LUCIA', 
    'MAR?A': 'MARIA', 
    'D?AZ': 'DIAZ', 
    'MU?OZ': 'MUÑOZ', 
    'MU EZ': 'MUÑOZ', 
    'BA?OS': 'BAÑOS', 
    'Í': 'I',

    # --- Entidades Especiales y Varios ---
    '&AMP;': '&', 
    '&QUOT;': '', 
    'Â®': '', 
    'Â': ' ', 
    '€': '', 
    'Âº': '', 
    '¡': 'I', 
    '': ' ', 
    '‹': '', 
    '›': '',

    # --- Nuevos Hallazgos Fase 3 (Big Data & UTF8-Lossy) ---
    'BAOS': 'BAÑOS',
    'SALDAA': 'SALDAÑA',
    'COMPAIA': 'COMPAÑIA',
    'NIO': 'NIÑO',
    'DISEO': 'DISEÑO',
    'AO': 'AÑO',
    'Ð': 'Ñ', 
    'ð': 'ñ', 
    '\ufffd': 'Ñ' 
}